import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import Footer from '../components/footer';
import Navbar from '../components/navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main></main>

      <Footer />
      <div>
        <Script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></Script>
        <Script src="https://unpkg.com/react/umd/react.production.min.js"></Script>
        <Script src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"></Script>
      </div>
    </div>
  );
}
